version: '3.3'
services:
  tomcatserver:
      image: gsanjeev/tomcat-mongodb-sboot-docker
      container_name: tomcat
      ports:
          - 8080
  #        - "8080:8080"
      hostname: tomcat
      links:
          - mongodb:mongo

  mongodb:
      image: mongo
      container_name: mongo
      ports:
          - 27017
      hostname: mongo
      volumes:
             - mongo-data:/var/lib/mongo/data
#    volumes:
#        - $HOME/mongo/data/db:/data/db
volumes:
  mongo-data:


  #browser:
  #    image: devurandom/firefox
  #    container_name: firefox
  #    links:
  #        - tomcatserver:tomcat
  #    hostname: firefox
  #    environment:
  #        - DISPLAY
  #    volumes:
  #        - /tmp/.X11-unix:/tmp/.X11-unix
  #        - $HOME:/home
  #    command: --new-instance tomcat:8080/ tomcat:8080/hits
